### ISSUE TITLE
Suggesting alternative to ejecting

### ISSUE THREAD

**Issue by mvanlonden** [grommet/grommet-react-app#2]
When ejecting you can't benefit from upstream `create-react-app` changes. Suggesting something like [grommet-css](https://github.com/mvanlonden/grommet-css) as an alternative.

**Comment by alansouzati** [comment]
sounds a good option. I believe folks that need theme capabilities under create-react-app could fork your grommet-css project and add their variables. Thanks for working on this.

I still would like to still keep this project in place with the ejected version so that folks that still SASS support could benefit from it. Hopefully it makes sense.

For this reason I'm closing this issue but feel free to re-open this if you think otherwise.

I think it would a great a idea for you to create a `grommet-react-app` that uses your `grommet-css`, I would happy to promote.

**Comment by mvanlonden** [comment]
Great! Yes I wouldn't want to replace this repo with grommet-css, it could
potentially be added to the readme as an alternative?

**Comment by alansouzati** [comment]
definitely. when you have that send it over to me. I will make sure to add that as an alternative 👍
